### ISSUE TITLE
CART -- As a User, I can ADD items to my cart from the product listing or product detail pages

### ISSUE THREAD

**Issue by ianmichaeld** [8BitBargains/8bitBargains#20]
- [x] Set up back end routing to add a game to cart/order
- [x] Can add items to cart from the 'All Products' browse page
- [x] Can add items to cart from an individual product page 
- [x] Adding an item that is already in the cart should update the quantity (add one)
- [x] Refactor so post and put routes are analogous

**Comment by dleistman** [comment]
- [ ] Can add items to cart from the 'All Products' browse page
- [ ] Can add items to cart from an individual product page
